### ISSUE TITLE
Any tools for visualizing the alignment in real-time?

### ISSUE THREAD

**Issue by C-Aniruddh** [robmaier/ldvo#1]

**Comment by robmaier** [comment]
While the code here is focused on pure odometry, you could easily extend the [ldvo_tracker example app](https://github.com/robmaier/ldvo/blob/master/examples/app_tracker.cpp) with some 2D/3D visualizations using [Pangolin](https://github.com/stevenlovegrove/Pangolin).

**Comment by C-Aniruddh** [comment]
Thank you! Figured it out!
