### ISSUE TITLE
estimated pose -nan 

### ISSUE THREAD

**Issue by florianspy** [robmaier/ldvo#2]
I tried to applying the source code to ros and use it with a realsense d435
however when i use bool ok = tracker.align(*prev_pyramid, *cur_pyramid, pose_prev_to_cur); 
i always get estimated pose:
-nan -nan -nan -nan
-nan -nan -nan -nan
-nan -nan -nan -nan
   0    0    0    1
here is the source code:
SubscribeAndPublish(int choose_):sync2(image_sub,image_sub2,500){
		image_sub.subscribe(n, "/camera/color/image_raw", 1);
		image_sub2.subscribe(n, "/camera/aligned_depth_to_color/image_raw", 1);
		sync2.registerCallback(boost::bind(&SubscribeAndPublish::callback,this, _1, _2));
		odom_pub = n.advertise<nav_msgs::Odometry>("LDVO", 50);
		choose=choose_;
		tracker_cfg.validate();
		tracker_cfg.print();
		boost::shared_ptr<sensor_msgs::CameraInfo const> cam_info = ros::topic::waitForMessage<sensor_msgs::CameraInfo>("/camera/color/camera_info",n);
		w = (*(cam_info)).width;
		h = (*(cam_info)).height;
		Eigen::Matrix3f K;
		K << (*(cam_info)).K[0], 0.0f, (*(cam_info)).K[2],
		     0.0f, (*(cam_info)).K[4], (*(cam_info)).K[5],
		     0.0f, 0.0f, 1.0f;
		camera = ldvo::CameraModel(w, h, K);
		// fill cv::Mat images (OpenCV)
		camera.print();
		// TODO fill previous frame
		pose_prev_to_cur = Eigen::Matrix4f::Identity();
	}
	void callback(const sensor_msgs::ImageConstPtr& msg,const sensor_msgs::ImageConstPtr& msg2){		//auto start = chrono::steady_clock::now();
		cv::Mat first =cv_bridge::toCvShare(msg)->image;
		ldvo::Tracker tracker(tracker_cfg, camera);
		cv::Mat depth = cv_bridge::toCvShare(msg2, "32FC1")->image;
		cv::Mat depth_flt;
		depth.convertTo(depth_flt, CV_32FC1);
		depth_flt.setTo(std::numeric_limits<float>::quiet_NaN(), depth == 0);
		depth = depth_flt.clone();
		cv::Mat gray;
		cv::cvtColor(first, gray, cv::COLOR_BGR2GRAY);
		if(gray_prev.empty()){	
			gray_prev= gray.clone();
			depth_prev = depth.clone();
			double time_color_prev=0, time_depth_prev=0;
			std::shared_ptr<ldvo::Frame> prev_frame= std::make_shared<ldvo::Frame>(w, h);
			prev_frame->fill(gray_prev, depth_prev, time_color_prev, time_depth_prev);
			int num_levels = tracker_cfg.num_levels;
			prev_pyramid =  std::make_shared<ldvo::FramePyramid>(w, h, num_levels);
			prev_pyramid->fill(*prev_frame);
		}
		else{
			cv::Mat gray_cur, depth_cur;
			double time_color_cur=0, time_depth_cur=0;
			gray_cur=gray.clone();
			depth_cur = depth.clone();
			std::shared_ptr<ldvo::Frame> cur_frame =
			        std::make_shared<ldvo::Frame>(w, h);
			cur_frame->fill(gray_cur, depth_cur, time_color_cur, time_depth_cur);
			int num_levels = tracker_cfg.num_levels;
			std::shared_ptr<ldvo::FramePyramid> cur_pyramid =
			        std::make_shared<ldvo::FramePyramid>(w, h, num_levels);
			cur_pyramid->fill(*cur_frame);
			bool ok = tracker.align(*prev_pyramid, *cur_pyramid, pose_prev_to_cur);
			if (ok)
			{
			    std::cout << "estimated pose:" << std::endl;
			    std::cout << pose_prev_to_cur << std::endl;
			}
			else
			{
			    std::cerr << "could not align frames!" << std::endl;
			}
		    std::swap(prev_pyramid, cur_pyramid);

		}
	}

**Comment by florianspy** [comment]
After looking into the provided source code i found out that the matrix containing the greyscale data needs to be adjusted to 32FC1 as well so putting the following line in gray.convertTo(gray, CV_32FC1, 1.0 / 255.0); after  cv::cvtColor(first, gray, cv::COLOR_BGR2GRAY); resolves the issue

**Comment by robmaier** [comment]
Thanks for the update.
I'm actually curious about how well the algorithm works with the RGB-D data from D435 sensors? My experiences with the Intel Realsense sensors have not been to good so far ...

**Comment by florianspy** [comment]
Are  there any other recommendations for prepoccesing of the image data?
Short feedback this is now the full source code we use for evaluation: 
class SubscribeAndPublish
{
public:
	SubscribeAndPublish(int choose_):sync2(image_sub,image_sub2,500){
		image_sub.subscribe(n, "/camera/color/image_raw", 1);
		image_sub2.subscribe(n, "/camera/aligned_depth_to_color/image_raw", 1);
		sync2.registerCallback(boost::bind(&SubscribeAndPublish::callback,this, _1, _2));
		odom_pub = n.advertise<nav_msgs::Odometry>("RGBDodom", 50);
		choose=choose_;
		tracker_cfg.validate();
		tracker_cfg.print();
		boost::shared_ptr<sensor_msgs::CameraInfo const> cam_info = ros::topic::waitForMessage<sensor_msgs::CameraInfo>("/camera/color/camera_info",n);
		w = (*(cam_info)).width;
		h = (*(cam_info)).height;
		Eigen::Matrix3f K;
		K << (*(cam_info)).K[0], 0.0f, (*(cam_info)).K[2],
		     0.0f, (*(cam_info)).K[4], (*(cam_info)).K[5],
		     0.0f, 0.0f, 1.0f;
		camera = ldvo::CameraModel(w, h, K);
		// fill cv::Mat images (OpenCV)
		camera.print();
		// TODO fill previous frame
		pose_prev_to_cur = Eigen::Matrix4f::Identity();

	}
	void callback(const sensor_msgs::ImageConstPtr& msg,const sensor_msgs::ImageConstPtr& msg2){		//auto start = chrono::steady_clock::now();
		cv::Mat first =cv_bridge::toCvShare(msg)->image;
		ldvo::Tracker tracker(tracker_cfg, camera);
		cv::Mat depth = cv_bridge::toCvShare(msg2, "32FC1")->image;
		cv::Mat depth_flt;
		depth.convertTo(depth_flt, CV_32FC1,(1.0/1000.0));
		depth_flt.setTo(std::numeric_limits<float>::quiet_NaN(), depth == 0);
		depth = depth_flt.clone();
		std::cout<<first.type()<<" ";
		cv::Mat gray;

		cv::cvtColor(first, gray, cv::COLOR_BGR2GRAY);
		std::cout<<gray.type();
		gray.convertTo(gray, CV_32FC1, 1.0 / 255.0);
		if(gray_prev.empty()){
			//https://docs.opencv.org/3.4/df/ddc/classcv_1_1rgbd_1_1Odometry.html needs metre
			gray_prev= gray.clone();
			depth_prev = depth.clone();
			double time_color_prev=0, time_depth_prev=0;
			std::shared_ptr<ldvo::Frame> prev_frame= std::make_shared<ldvo::Frame>(w, h);
			prev_frame->fill(gray_prev, depth_prev, time_color_prev, time_depth_prev);
			int num_levels = tracker_cfg.num_levels;
			prev_pyramid =  std::make_shared<ldvo::FramePyramid>(w, h, num_levels);
			prev_pyramid->fill(*prev_frame);
		}
		else{
			cv::Mat gray_cur, depth_cur;
			double time_color_cur=0, time_depth_cur=0;
			gray_cur=gray.clone();
			depth_cur = depth.clone();
			std::shared_ptr<ldvo::Frame> cur_frame =
			        std::make_shared<ldvo::Frame>(w, h);
			cur_frame->fill(gray_cur, depth_cur, time_color_cur, time_depth_cur);
			int num_levels = tracker_cfg.num_levels;
			std::shared_ptr<ldvo::FramePyramid> cur_pyramid =
			        std::make_shared<ldvo::FramePyramid>(w, h, num_levels);
			cur_pyramid->fill(*cur_frame);
			Eigen::Matrix4f pose_prev_to_cur2 = Eigen::Matrix4f::Identity();
			bool ok = tracker.align(*prev_pyramid, *cur_pyramid, pose_prev_to_cur2);
			if (ok)
			{
			    std::cout << "estimated pose:" << std::endl;
			    pose_prev_to_cur=pose_prev_to_cur*pose_prev_to_cur2;
			    std::cout <<pose_prev_to_cur  << std::endl;
			}
			else
			{
			    std::cerr << "could not align frames!" << std::endl;
			}
		    std::swap(prev_pyramid, cur_pyramid);

		}
	}
private:
	ros::NodeHandle n;
	ros::Publisher odom_pub;
	message_filters::Subscriber<Image> image_sub;
	message_filters::Subscriber<Image> image_sub2;
	TimeSynchronizer<Image, Image> sync2;
	ldvo::Tracker::Config tracker_cfg;
	Eigen::Matrix3f K;
	ldvo::CameraModel camera;
	cv::Mat gray_prev, depth_prev;
	int choose;
	int w;
	int h;
	Eigen::Matrix4f pose_prev_to_cur;
	std::shared_ptr<ldvo::FramePyramid> prev_pyramid;
};
int main(int argc, char **argv){
	ros::init(argc, argv,  "talker");
		SubscribeAndPublish test(1);
		ros::spin();
		return 1;

}
We get kinda okay results for slow movements in x or z direction,e.g.:
   0.998461  0.00566949   0.0551753  -0.0209618
-0.00543213    0.999975 -0.00445092 0.000522596
 -0.0551992  0.00414435    0.998467  0.00406046
          0           0           0           1
16 0estimated pose:
   0.997977  0.00439547   0.0634297  -0.0255602
 -0.0040352    0.999975 -0.00580687  0.00531848
 -0.0634537  0.00553916    0.997969     0.00483
          0           0           0           1

**Comment by raymanfx** [comment]
Hi, sorry for hijacking this thread.
I'm also using a RealSense D435 for a SLAM project (have it mounted on a GoPiGo3 robot).
Originally I planned on using the OpenCV RGBD Odometry implementation: https://docs.opencv.org/3.4/d0/d60/classcv_1_1rgbd_1_1RgbdOdometry.html. It should be implemented following the 2011 paper as well, so pretty close to your implementation I guess?

You added the Huber loss function to your code, did you do any comparison at TUM between the old code and the new one with the robust loss function?

For the record, I'm also able to get okay-ish translation data for x/z movement, but my rotation data from the rigid body motion estimation appears to be a bit off at times.
Anyway, my current implementation is centered around the OpenCV RGBD classes, but I want to try out ldvo later this month.

**Comment by robmaier** [comment]
Hi Christopher,
honestly, I have not evaluated the implementation in this repository too much w.r.t. any benchmarks except of a few sequences. This code was mostly developed for teaching purposes and consequently there should be quite some room for optimization...
