### ISSUE TITLE
freiburg2_pioneer_slam accuracy

### ISSUE THREAD

**Issue by raymanfx** [robmaier/ldvo#3]
Dataset: https://vision.in.tum.de/rgbd/dataset/freiburg2/rgbd_dataset_freiburg2_pioneer_slam.tgz

Commands used:
```
cd data
python2 associate.py fr2_slam/rgb.txt fr2_slam/depth.txt > fr2_slam/rgbd_assoc.txt
cd ../build
./ldvo_tracker -i ../data/fr2_slam/ -c ../data/intrinsics_fr2.txt -p poses.txt --levels 5 --min_level 1 --max_depth 1.5 --update_thres 0.001
python2 ../data/evaluate_ate.py ../data/fr2_slam/groundtruth.txt poses.txt --plot plot.png --verbose
```

Output:
```
compared_pose_pairs 2171 pairs
absolute_translational_error.rmse 14.328729 m
absolute_translational_error.mean 12.494327 m
absolute_translational_error.median 10.357368 m
absolute_translational_error.std 7.014574 m
absolute_translational_error.min 4.346162 m
absolute_translational_error.max 61.631673 m
```

Adjusting max_depth to 10.0 yields the following (improved) results:
```
absolute_translational_error.rmse 5.990061 m
absolute_translational_error.mean 5.062975 m
absolute_translational_error.median 3.805372 m
absolute_translational_error.std 3.201112 m
absolute_translational_error.min 0.671174 m
absolute_translational_error.max 12.364352 m
```

The error is still pretty high though. Do you know whether this is related to the algorithm in general or could it be caused by implementation issues in this code?

**Comment by robmaier** [comment]
Hi Christopher,
hmm, good question. As I mentioned in the other issue, I have not evaluated the implementation in this repository too much. 
But in principle it holds that: the longer the trajectory, the larger the error without loop closure. The drift seems still very large though from the numbers and I think that tracking gets simply lost. I guess it would be more promising in your case to look for a full SLAM system such as ORB-SLAM/ORB-SLAM2 or DVO-SLAM or BundleFusion or BAD-SLAM or so ...
