### ISSUE TITLE
RPE results of paper

### ISSUE THREAD

**Issue by liyang-huang** [robmaier/ldvo#5]
Hi robmaier,

How do I set the parameters to get the same RPE as in the paper?
Can you give me some advice on that?

Steinbruecker et al, ICCVW 2011:
RPE: 0.0053m/f , 0.0065 deg/f

My results:
RPE: 0.009129m/f , 0.592854 deg/f

thanks

**Comment by robmaier** [comment]
Since this is neither the "official" implementation of the paper nor optimized towards the respective benchmark sequences, I unfortunately cannot give you any advice towards achieving that...
